### PR TITLE
Migrate to null safety

### PR DESCRIPTION
**Pull request by smkhalsa**

### CODE REVIEW

**Comment by smkhalsa** [comment]
@letsar thoughts on this?

**Comment by sazzadshopno** [comment]
Is there any way to expand Scatter to fit its parent width?
I have this
Image

I want black background to expand and fit the circles within it
Image

**Comment by chirgwin** [comment]
@smkhalsa Thanks for this. For folks like me wanting to use this prior to its merge/release, adding the following to `pubspec.yaml` worked for me:
```
  flutter_scatter:
    git:
      url: git@github.com:smkhalsa/flutter_scatter.git
      ref: null-safety
```

**Comment by letsar** [comment]
Thanks for this PR, but I'll do it myself today since I have some time and it will avoid some back and forth ;-).

**Pull request closed without merging**
